name: Deploy Auth
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup kubectl and deploy
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_SECRET }}
      - name: Create namespace if it doesn't exist
        run: |
          kubectl create namespace real-time-analytics --dry-run=client -o yaml | kubectl apply -f -
      - name: Create Kubernetes Secrets
        run: |
          kubectl create secret generic rta-auth-secret \
            --from-literal=DB_USER=${{ secrets.POSTGRES_USER }} \
            --from-literal=DB_PASS=${{ secrets.POSTGRES_PASSWORD }} \
            --from-literal=DB_NAME=${{ secrets.POSTGRES_DB }} \
            --from-literal=DB_PORT=${{ secrets.POSTGRES_PORT }} \
            --from-literal=HOST=${{ secrets.AUTH_HOST}} \
            --from-literal=PORT=${{ secrets.AUTH_PORT}} \
            --from-literal=JWT_SECRET=${{ secrets.JWT_SECRET}} \
            -n real-time-analytics --dry-run=client -o yaml | kubectl apply -f -
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f .k8s/auth-deployment.yaml -n real-time-analytics
          kubectl apply -f .k8s/auth-service.yaml -n real-time-analytics
          kubectl apply -f .k8s/auth-ingress.yaml -n real-time-analytics